name: Deploy TWIP Path WEB app to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.x'

      - name: Install dependencies
        run: flutter pub get

      - name: Build web app
        run: flutter build web --base-href "/resume_builder/"

      - name: Upload static files
        uses: actions/upload-pages-artifact@v1
        with:
          path: build/web

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
